services:
  activemq:
    image: 'apache/activemq-classic:latest@sha256:161c74e25d14c0981c73686bd03d8a7682ae3aa7527e551b568a8a865568be2d'
    ports:
      - '61616'
  artemis:
    image: 'apache/activemq-artemis:latest@sha256:bae523439ee32f45b204d065a60bf49438e8a52764a39023065933633c61b1c7'
    ports:
      - '61616'
  azurite:
    image: 'mcr.microsoft.com/azure-storage/azurite:latest@sha256:47a392f1c93a6b639999fc505dcae348e350183b47f2a7526c765ddd7fa56e0e'
    ports:
      - '10000'
      - '10001'
      - '10002'
  cassandra:
    image: 'cassandra:latest@sha256:b4aa0515fad675cacce222b6d07ebd8a7052303d725e819b260a7f4b0ddef65e'
    environment:
      - 'CASSANDRA_DC=dc1'
      - 'CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch'
    ports:
      - '9042'
  chroma:
    image: 'chromadb/chroma:latest@sha256:b0c16c6b1b47b28150ad6ba9b8eb9da4752dc6cf4df1078ee821c2fc897dfc4e'
    ports:
      - '8000'
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.10@sha256:bc7ba1dc5067c5b3907b82c667a374cc987cd813501e1378ec74ccd1c577f787'
    environment:
      - 'ELASTIC_PASSWORD=secret'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - '9200'
      - '9300'
  mariadb:
    image: 'mariadb:latest@sha256:4066f2d4805fef72a83cf4a62689a0aadb6e83a8c8a82b64431edd4b94f684f8'
    environment:
      - 'MARIADB_DATABASE=mydatabase'
      - 'MARIADB_PASSWORD=secret'
      - 'MARIADB_ROOT_PASSWORD=verysecret'
      - 'MARIADB_USER=myuser'
    ports:
      - '3306'
  mongodb:
    image: 'mongo:latest@sha256:a3d0dec40b95df592c7e7eef603019ba03b164998c3b394739e0dd4cd45d490d'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017'
  mysql:
    image: 'mysql:latest@sha256:c69299937e5e2fc9a2cb26f5cd7a7151e48d9d5a3b3679f62bfd1275de698c0c'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'
  neo4j:
    image: 'neo4j:latest@sha256:0dd89bd6f1f6842b1050c09b439a070d86e3dde5865e2bdd71ee7e4c47abeb60'
    environment:
      - 'NEO4J_AUTH=neo4j/notverysecret'
    ports:
      - '7687'
  ollama:
    image: 'ollama/ollama:latest@sha256:a45c1ae866f0ad115b5b2b5048cb80e02a8c49c36f60d49f449b0d6a3825cdbf'
    ports:
      - '11434'
  oracle:
    image: 'gvenzl/oracle-free:latest@sha256:02c54fd1dad4b698730be9b78ffd01a0c4b6e31d96c991a49e3cba842ebc4b9e'
    environment:
      - 'ORACLE_PASSWORD=secret'
    ports:
      - '1521'
  pgvector:
    image: 'pgvector/pgvector:pg16@sha256:7bbb2558b9b73d23c4a7795d7a016cbb531ef5fb1e231115fa1aeac5129caf10'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432'
  pulsar:
    image: 'apachepulsar/pulsar:latest@sha256:db2b860009fc22b9916df8b50b2549deb37a28f78033573b06a60b6fc217cf64'
    ports:
      - '6650'
      - '8080'
    command: 'bin/pulsar standalone'
  qdrant:
    image: 'qdrant/qdrant:latest@sha256:ebb521830cbfa8a8194d8ee71de6fbe75aea67a6373e4b11e1a4d7f4e80e356d'
    ports:
      - '6334'
  rabbitmq:
    image: 'rabbitmq:latest@sha256:1f5970642b6ecce21c6a875069ab6796f86cdecc65f2651ede3b23b6b2f8616b'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672'
  redis:
    image: 'redis/redis-stack:latest@sha256:ee18d7ce6f3e9e9ddc315d8cb4e2db11e76bc89f52a35405aa5dac330421d98f'
    labels:
      - "org.springframework.boot.service-connection=redis"
    ports:
      - '6379'
  sqlserver:
    image: 'mcr.microsoft.com/mssql/server:latest@sha256:8ca3956bcb1f3373e5b04f946a527abb24c07655c2044bd5c9c8852d02fbec7c'
    environment:
      - 'ACCEPT_EULA=yes'
      - 'MSSQL_PID=express'
      - 'MSSQL_SA_PASSWORD=verYs3cret'
    ports:
      - '1433'
  weaviate:
    image: 'semitechnologies/weaviate:latest@sha256:8e31d5a870d8cb54cb291434f9786f951700c19525db6d735f1668a972cdf145'
    ports:
      - '8080'
  zipkin:
    image: 'openzipkin/zipkin:latest@sha256:a7c69b5d23676a3cf7538ad8d9125f77fb2c8b72fc72bbca21357a3e984ac1bc'
    ports:
      - '9411'
