services:
  activemq:
    image: 'apache/activemq-classic:latest@sha256:161c74e25d14c0981c73686bd03d8a7682ae3aa7527e551b568a8a865568be2d'
    ports:
      - '61616'
  artemis:
    image: 'apache/activemq-artemis:latest@sha256:ac0fd145c160510fc721ca3d806df5592efa2abb537905f878b3c23a72dd932f'
    ports:
      - '61616'
  cassandra:
    image: 'cassandra:latest@sha256:9194f97b286a47a537281e8ca5e1e2d90686624d28264f669bd87799c58a3e67'
    environment:
      - 'CASSANDRA_DC=dc1'
      - 'CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch'
    ports:
      - '9042'
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.10@sha256:bc7ba1dc5067c5b3907b82c667a374cc987cd813501e1378ec74ccd1c577f787'
    environment:
      - 'ELASTIC_PASSWORD=secret'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - '9200'
      - '9300'
  mariadb:
    image: 'mariadb:latest@sha256:e59ba8783bf7bc02a4779f103bb0d8751ac0e10f9471089709608377eded7aa8'
    environment:
      - 'MARIADB_DATABASE=mydatabase'
      - 'MARIADB_PASSWORD=secret'
      - 'MARIADB_ROOT_PASSWORD=verysecret'
      - 'MARIADB_USER=myuser'
    ports:
      - '3306'
  mongodb:
    image: 'mongo:latest@sha256:54996a559c724c726a31fb8131e1c9088a05f7e531760e2897212389bbf20fed'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017'
  mysql:
    image: 'mysql:latest@sha256:72a37ddc9f839cfd84f1f6815fb31ba26f37f4c200b90e49607797480e3be446'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'
  neo4j:
    image: 'neo4j:latest@sha256:fd01c22d482011718d40120796204226ff555bbe14a1060519c862acd94f4670'
    environment:
      - 'NEO4J_AUTH=neo4j/notverysecret'
    ports:
      - '7687'
  oracle:
    image: 'gvenzl/oracle-free:latest@sha256:34a3d49815a75085c39a098ebc7ce06a6947d318108ef8191bf4a27dabc52925'
    environment:
      - 'ORACLE_PASSWORD=secret'
    ports:
      - '1521'
  pgvector:
    image: 'pgvector/pgvector:pg16@sha256:95732f8f93a33bcd427b8e0e8f9d8ceedb5256a6fe5f2b58a4cd78e943c7e30e'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432'
  pulsar:
    image: 'apachepulsar/pulsar:latest@sha256:bc40b0d47b7ba2e5de85c4d95a5b5acbd6f1a7c0865d4306a7f3f87fa75a8fbc'
    ports:
      - '6650'
      - '8080'
    command: 'bin/pulsar standalone'
  rabbitmq:
    image: 'rabbitmq:latest@sha256:a4a94e3ef4929e4cb8589f34a993f34e15de93c1f72a426664c5df422abec572'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672'
  redis:
    image: 'redis:latest@sha256:fb534a36ac2034a6374933467d971fbcbfa5d213805507f560d564851a720355'
    ports:
      - '6379'
  sqlserver:
    image: 'mcr.microsoft.com/mssql/server:latest@sha256:c4369c38385eba011c10906dc8892425831275bb035d5ce69656da8e29de50d8'
    environment:
      - 'ACCEPT_EULA=yes'
      - 'MSSQL_PID=express'
      - 'MSSQL_SA_PASSWORD=verYs3cret'
    ports:
      - '1433'
  zipkin:
    image: 'openzipkin/zipkin:latest@sha256:da8177371c4a7aed7fd673196593c2ff104ce908f300e1971493587622f7a297'
    ports:
      - '9411'
