services:
  activemq:
    image: 'apache/activemq-classic:latest@sha256:161c74e25d14c0981c73686bd03d8a7682ae3aa7527e551b568a8a865568be2d'
    ports:
      - '61616'
  artemis:
    image: 'apache/activemq-artemis:latest@sha256:bae523439ee32f45b204d065a60bf49438e8a52764a39023065933633c61b1c7'
    ports:
      - '61616'
  cassandra:
    image: 'cassandra:latest@sha256:ce90900ccd2bdc83bf21bb04f338d2f6321d48d448d49183dca6cc4322347d60'
    environment:
      - 'CASSANDRA_DC=dc1'
      - 'CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch'
    ports:
      - '9042'
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.10@sha256:bc7ba1dc5067c5b3907b82c667a374cc987cd813501e1378ec74ccd1c577f787'
    environment:
      - 'ELASTIC_PASSWORD=secret'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - '9200'
      - '9300'
  mariadb:
    image: 'mariadb:latest@sha256:4b812bbd9a025569fbe5a7a70e4a3cd3af53aa36621fecb1c2e108af2113450a'
    environment:
      - 'MARIADB_DATABASE=mydatabase'
      - 'MARIADB_PASSWORD=secret'
      - 'MARIADB_ROOT_PASSWORD=verysecret'
      - 'MARIADB_USER=myuser'
    ports:
      - '3306'
  mongodb:
    image: 'mongo:latest@sha256:ae1cf99fa7bfb007db8416ad4f3980c46054d949fa55d28e6d301a813fee6c06'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017'
  mysql:
    image: 'mysql:latest@sha256:86cdfe832c81e39a89cfb63c3fde1683c41cc00ef91e67653c9c1df0ba80f454'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'
  neo4j:
    image: 'neo4j:latest@sha256:6dcf2bdb9cc227325dd99cfb40712d47c746993150e2ce523ca1e1a72521605d'
    environment:
      - 'NEO4J_AUTH=neo4j/notverysecret'
    ports:
      - '7687'
  oracle:
    image: 'gvenzl/oracle-free:latest@sha256:12843a218f6bbb4eba193107786d676baed80b8a318a4d4f592c52c7ea1e77fb'
    environment:
      - 'ORACLE_PASSWORD=secret'
    ports:
      - '1521'
  pgvector:
    image: 'pgvector/pgvector:pg16@sha256:7bbb2558b9b73d23c4a7795d7a016cbb531ef5fb1e231115fa1aeac5129caf10'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432'
  pulsar:
    image: 'apachepulsar/pulsar:latest@sha256:db2b860009fc22b9916df8b50b2549deb37a28f78033573b06a60b6fc217cf64'
    ports:
      - '6650'
      - '8080'
    command: 'bin/pulsar standalone'
  rabbitmq:
    image: 'rabbitmq:latest@sha256:4614541e23da00ea3a854005808939c82691aeb63ce6233e0a312cf2ef93b9c7'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672'
  redis:
    image: 'redis:latest@sha256:878983f8f5045b28384fc300268cec62bca3b14d5e1a448bec21f28cfcc7bf78'
    ports:
      - '6379'
  sqlserver:
    image: 'mcr.microsoft.com/mssql/server:latest@sha256:c1aa8afe9b06eab64c9774a4802dcd032205d1be785b1fd51e1c0151e7586b74'
    environment:
      - 'ACCEPT_EULA=yes'
      - 'MSSQL_PID=express'
      - 'MSSQL_SA_PASSWORD=verYs3cret'
    ports:
      - '1433'
  zipkin:
    image: 'openzipkin/zipkin:latest@sha256:a7c69b5d23676a3cf7538ad8d9125f77fb2c8b72fc72bbca21357a3e984ac1bc'
    ports:
      - '9411'
