on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - 17
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin

      - run: mvn dependency:tree

      - run: mvn dependency:resolve-plugins
