on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - 17
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin

      - run: mvn --version

      - run: ./mvnw --version

      - run: mvn dependency:tree -DoutputFile=dependency-tree.txt

      - run: mvn dependency:resolve-plugins -DoutputFile=plugin-tree.txt

      - run: mvn help:effective-pom -Doutput=effective-pom.xml

      - run: mvn -f noparent-pom.xml dependency:tree -DoutputFile=noparent-dependency-tree.txt

      - run: mvn -f noparent-pom.xml dependency:resolve-plugins -DoutputFile=noparent-plugin-tree.txt

      - run: mvn -f noparent-pom.xml help:effective-pom -Doutput=noparent-effective-pom.xml
