on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

jobs:
  dependency:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - 21

    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin

      - run: mvn --version

      - run: ./mvnw --version

      - run: |
          ./mvnw help:effective-pom -Doutput=effective-pom.xml
          ./mvnw -f noparent/pom.xml help:effective-pom -Doutput=effective-pom.xml
          # ./mvnw -f milestone/pom.xml help:effective-pom -Doutput=effective-pom.xml

      - run: |
          ./mvnw dependency:tree -DoutputFile=dependency-tree.txt
          ./mvnw -f noparent/pom.xml dependency:tree -DoutputFile=dependency-tree.txt
          # ./mvnw -f milestone/pom.xml dependency:tree -DoutputFile=dependency-tree.txt

      - run: |
          ./mvnw dependency:resolve-plugins -DoutputFile=resolve-plugins.txt
          ./mvnw -f noparent/pom.xml dependency:resolve-plugins -DoutputFile=resolve-plugins.txt
          # ./mvnw -f milestone/pom.xml dependency:resolve-plugins -DoutputFile=resolve-plugins.txt

      - uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e # v6
        with:
          title: effective-dependency
          body:
          commit-message: effective-dependency
          branch: effective-dependency
