on:
  workflow_dispatch:
  schedule:
    - cron:  '* * * * *'
jobs:
  dependency:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - 21
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin

      - run: mvn --version

      - run: ./mvnw --version

      - run: |
          ./mvnw versions:update-parent
          ./mvnw versions:update-child-modules
          ./mvnw versions:update-properties
          # ./mvnw versions:use-latest-snapshots
          ./mvnw versions:use-latest-releases

      - run: |
          cd noparent
          ../mvnw versions:update-parent
          ../mvnw versions:update-child-modules
          ../mvnw versions:update-properties
          # ../mvnw versions:use-latest-snapshots
          ../mvnw versions:use-latest-releases

      - uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5
