on:
  workflow_dispatch:
  schedule:
    - cron:  '* * * * *'
jobs:
  dependency:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - 21
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: actions/setup-java@5896cecc08fd8a1fbdfaf517e29b571164b031f7 # v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin

      - run: mvn --version

      - run: ./mvnw --version

      - run: |
          ./mvnw versions:update-parent
          ./mvnw versions:update-child-modules
          ./mvnw versions:update-properties
          # ./mvnw versions:use-latest-snapshots
          ./mvnw versions:use-latest-releases

      - run: |
          cd noparent
          ../mvnw versions:update-parent
          ../mvnw versions:update-child-modules
          ../mvnw versions:update-properties
          # ../mvnw versions:use-latest-snapshots
          ../mvnw versions:use-latest-releases

      - uses: peter-evans/create-pull-request@70a41aba780001da0a30141984ae2a0c95d8704e # v6
