on:
  workflow_dispatch:
  schedule:
    - cron:  '* * * * *'
jobs:
  dependency:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - 21
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin

      - run: mvn --version

      - run: ./mvnw --version

      - run: |
          ./mvnw versions:update-parent
          ./mvnw versions:update-child-modules
          ./mvnw versions:update-properties
          # ./mvnw versions:use-latest-snapshots
          ./mvnw versions:use-latest-releases

      - run: |
          cd noparent
          ../mvnw versions:update-parent
          ../mvnw versions:update-child-modules
          ../mvnw versions:update-properties
          # ../mvnw versions:use-latest-snapshots
          ../mvnw versions:use-latest-releases

      - uses: peter-evans/create-pull-request@9153d834b60caba6d51c9b9510b087acf9f33f83 # v6
        with:
          title: versions-update
          body:
          commit-message: versions-update
          branch: versions-update
